-- AlterEnum
-- This migration adds more than one value to an enum.
-- With PostgreSQL versions 11 and earlier, this is not possible
-- in a single migration. This can be worked around by creating
-- multiple migrations, each migration adding only one value to
-- the enum.


ALTER TYPE "Role" ADD VALUE 'OWNER';
ALTER TYPE "Role" ADD VALUE 'SUPERVISOR';
ALTER TYPE "Role" ADD VALUE 'ACCOUNTANT';
ALTER TYPE "Role" ADD VALUE 'INVENTORY_MANAGER';
ALTER TYPE "Role" ADD VALUE 'EMPLOYEE';
ALTER TYPE "Role" ADD VALUE 'SALES_ASSOCIATE';
ALTER TYPE "Role" ADD VALUE 'MERCHANDISER';
ALTER TYPE "Role" ADD VALUE 'STORE_CLERK';
ALTER TYPE "Role" ADD VALUE 'CHEF';
ALTER TYPE "Role" ADD VALUE 'SOUS_CHEF';
ALTER TYPE "Role" ADD VALUE 'BARTENDER';
ALTER TYPE "Role" ADD VALUE 'HOST';
ALTER TYPE "Role" ADD VALUE 'KITCHEN_STAFF';
ALTER TYPE "Role" ADD VALUE 'CONCIERGE';
ALTER TYPE "Role" ADD VALUE 'HOUSEKEEPER';
ALTER TYPE "Role" ADD VALUE 'MAINTENANCE';
ALTER TYPE "Role" ADD VALUE 'BELLHOP';
ALTER TYPE "Role" ADD VALUE 'STYLIST';
ALTER TYPE "Role" ADD VALUE 'BEAUTICIAN';
ALTER TYPE "Role" ADD VALUE 'THERAPIST';
ALTER TYPE "Role" ADD VALUE 'TECHNICIAN';
ALTER TYPE "Role" ADD VALUE 'PHARMACIST';
ALTER TYPE "Role" ADD VALUE 'PHARMACY_TECH';
ALTER TYPE "Role" ADD VALUE 'DOCTOR';
ALTER TYPE "Role" ADD VALUE 'NURSE';
ALTER TYPE "Role" ADD VALUE 'BUTCHER';
ALTER TYPE "Role" ADD VALUE 'BAKER';
ALTER TYPE "Role" ADD VALUE 'PRODUCE_MANAGER';
ALTER TYPE "Role" ADD VALUE 'DELI_WORKER';
ALTER TYPE "Role" ADD VALUE 'TEACHER';
ALTER TYPE "Role" ADD VALUE 'INSTRUCTOR';
ALTER TYPE "Role" ADD VALUE 'ADMINISTRATOR';
ALTER TYPE "Role" ADD VALUE 'DRIVER';
ALTER TYPE "Role" ADD VALUE 'MECHANIC';
ALTER TYPE "Role" ADD VALUE 'DISPATCHER';
ALTER TYPE "Role" ADD VALUE 'FOREMAN';
ALTER TYPE "Role" ADD VALUE 'CONTRACTOR';
ALTER TYPE "Role" ADD VALUE 'SITE_MANAGER';
ALTER TYPE "Role" ADD VALUE 'TECH_SUPPORT';
ALTER TYPE "Role" ADD VALUE 'NETWORK_ADMIN';
ALTER TYPE "Role" ADD VALUE 'EVENT_COORDINATOR';
ALTER TYPE "Role" ADD VALUE 'DECORATOR';
ALTER TYPE "Role" ADD VALUE 'SECURITY_GUARD';
ALTER TYPE "Role" ADD VALUE 'SECURITY_MANAGER';
ALTER TYPE "Role" ADD VALUE 'VIEWER';
